// import { factoryMethod } from './creational/factory-method/factory-method';
// import { abstractFactory } from './creational/abstract-factory/abstract-factory';
// import { builder } from './creational/builder/builder';
// import { prototype } from './creational/prototype/prototype';
// import { singleton } from './creational/singleton/singleton';
// import { adapter } from './structural/adapter/adapter';
// import { bridge } from './structural/bridge/bridge';
// import { composite } from './structural/composite/composite';
// import { decorator } from './structural/decorator/decorator';
// import { facade } from './structural/facade/facade';
// import { flyweight } from './structural/flyweight/flyweight';
// import { proxy } from './structural/proxy/proxy';
// import { chainOfResponsibility } from './behavioral/chain-of-responsibility/chain-of-responsibility';
// import { command } from './behavioral/command/command';
// import { iterator } from './behavioral/iterator/iterator';
// import { mediator } from './behavioral/mediator/mediator';
// import { memento } from './behavioral/memento/memento';
// import { observer } from './behavioral/observer/observer';
// import { state } from './behavioral/state/state';
// import { strategy } from './behavioral/strategy/strategy';
import { templateMethod } from './behavioral/template-method/template-method';

console.log('============================================= START ====================================================');

// factoryMethod();
// abstractFactory();
// builder();
// prototype();
// singleton();
// adapter();
// bridge();
// composite();
// decorator();
// facade();
// flyweight();
// proxy();
// chainOfResponsibility();
// command();
// iterator();
// mediator();
// memento();
// observer();
// state();
// strategy();
templateMethod();

console.log('============================================== END =====================================================');
